### ISSUE TITLE
Use a secret has a nixos option value

### ISSUE THREAD

**Issue by JulienMalka** [Mic92/sops-nix#162] opened 2022-02-26 20:36 UTC
Hello,
I’d like to know if there is a way to use a nix sops secret as a value of a nixos option ? Some module don’t have things like « passwordFile » options but only « password ». In these kind of cases I never know what to do.

**Comment by dasJ** [comment] 2022-03-03 19:41
Possibly a duplicate of #159?

**Comment by Mic92** [comment] 2022-03-04 10:49
Agreed. This is a documented limitation of the design.

**Closed by Mic92** 2022-03-04 10:49 UTC
